spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_app
    username: myusername
    password: mypassword
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-paltform: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: 635166546A576E5A7234753778214125442A472D4A614E645267556B58703273357638792F423F4528482B4D6250655368566D597133743677397A2443264629
