spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_app
    username: myusername
    password: mypassword
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-paltform: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    header: Authorization ("\${jwt.header}")
    secret: mySecret
    expiration: 604800
    route:
      authentication:
        path: auth
        refresh: refresh